version: "3.9"
services:
  postgres:
    image: bitnami/postgresql:16
    environment:
      POSTGRESQL_USER: admin
      POSTGRESQL_PASSWORD: admin
      POSTGRESQL_DATABASE: repro
    ports:
      - 5432:5432
    volumes:
      - ./sql/psql_init.sql:/docker-entrypoint-initdb.d/psql_init.sql
